name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download and extract tarpaulin
        run: |
          wget https://github.com/xd009642/tarpaulin/releases/download/0.16.0/cargo-tarpaulin-0.16.0-travis.tar.gz
          tar xvzf cargo-tarpaulin-0.16.0-travis.tar.gz
      - name: Generate code coverage
        run: ./cargo-tarpaulin tarpaulin --verbose --no-default-features --workspace --timeout 120 --out Xml
      - name: Upload to codecov.io
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
