name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install SDL and Python
      run: sudo apt install -y libsdl2-dev python
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build lingonsylt documentation
      run: (cd docs && python3 mad_doc.py docs.json)
    - name: Upload docs
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: |
          docs/docs.html
